# NicoBot - Nicovideo player bot for discord, written from the scratch
# Copyright (C) 2020 Wonjun Jung (Kokosei J)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

HELLO = "HELLO"
READY = "READY"
RESUMED = "RESUMED"
RECONNECT = "RECONNECT"
INVALID_SESSION = "INVALID_SESSION"
CHANNEL_CREATE = "CHANNEL_CREATE"
CHANNEL_UPDATE = "CHANNEL_UPDATE"
CHANNEL_DELETE = "CHANNEL_DELETE"
CHANNEL_PINS_UPDATE = "CHANNEL_PINS_UPDATE"
GUILD_CREATE = "GUILD_CREATE"
GUILD_UPDATE = "GUILD_UPDATE"
GUILD_DELETE = "GUILD_DELETE"
GUILD_BAN_ADD = "GUILD_BAN_ADD"
GUILD_BAN_REMOVE = "GUILD_BAN_REMOVE"
GUILD_EMOJIS_UPDATE = "GUILD_EMOJIS_UPDATE"
GUILD_INTEGRATIONS_UPDATE = "GUILD_INTEGRATIONS_UPDATE"
GUILD_MEMBER_ADD = "GUILD_MEMBER_ADD"
GUILD_MEMBER_REMOVE = "GUILD_MEMBER_REMOVE"
GUILD_MEMBER_UPDATE = "GUILD_MEMBER_UPDATE"
GUILD_MEMBERS_CHUNK = "GUILD_MEMBERS_CHUNK"
GUILD_ROLE_CREATE = "GUILD_ROLE_CREATE"
GUILD_ROLE_UPDATE = "GUILD_ROLE_UPDATE"
GUILD_ROLE_DELETE = "GUILD_ROLE_DELETE"
INVITE_CREATE = "INVITE_CREATE"
INVITE_DELETE = "INVITE_DELETE"
MESSAGE_CREATE = "MESSAGE_CREATE"
MESSAGE_UPDATE = "MESSAGE_UPDATE"
MESSAGE_DELETE = "MESSAGE_DELETE"
MESSAGE_DELETE_BULK = "MESSAGE_DELETE_BULK"
MESSAGE_REACTION_ADD = "MESSAGE_REACTION_ADD"
MESSAGE_REACTION_REMOVE = "MESSAGE_REACTION_REMOVE"
MESSAGE_REACTION_REMOVE_ALL = "MESSAGE_REACTION_REMOVE_ALL"
MESSAGE_REACTION_REMOVE_EMOJI = "MESSAGE_REACTION_REMOVE_EMOJI"
PRESENCE_UPDATE = "PRESENCE_UPDATE"
TYPING_START = "TYPING_START"
USER_UPDATE = "USER_UPDATE"
VOICE_STATE_UPDATE = "VOICE_STATE_UPDATE"
VOICE_SERVER_UPDATE = "VOICE_SERVER_UPDATE"
WEBHOOKS_UPDATE = "WEBHOOKS_UPDATE"
